### ISSUE TITLE
spacemacs does not find elpy layer

### ISSUE THREAD

**Issue by mirkov** [rgemulla/spacemacs-layers#1]
When loading the .spacemacs file, the elpy layer fails.  

I did not download it explicitly, assuming it would be found automatically.

What is the recommended way of installing the elpy layer?  

I include my installation info below.  Emacs and python are provided via MSYS2.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.3
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. 26b8fe0c3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python html helm emacs-lisp git org common-lisp latex)
```

Thank you,

**Comment by rgemulla** [comment]
Somewhat late, but I just saw this. You will need to copy the elpy layer from [here](https://github.com/rgemulla/spacemacs-layers/tree/master/+lang/elpy) to `~/.spacemacs.d/private`.

Note that I personally switched to the pythonp layer (which also uses some parts of elpy), so the elpy layer is unmaintained.
